import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from 'react';
import {
  Activity, ArrowRight, BarChart3, Bell, Check, ChevronDown, CircleHelp, ClipboardCheck,
  Download, FileText, Filter, Flag, LayoutDashboard, LogOut, Map as MapIcon, MapPin,
  MessageSquare, Plus, Search, Settings, ShieldCheck, Sparkles, Upload, Users, X
} from 'lucide-react';
import { onNotice, request } from './api';
import { downloadEncryptedBackup } from './backup';
import { disablePush, enablePush, pushAvailable } from './push';
import { TurnstileChallenge } from './Turnstile';
import { IssueMap, LocationPicker } from './MapViews';
import type { AreaSummary, Category, Complaint, ComplaintDetail, Department, Feedback, PageResult, Performance, Snapshot, User } from './types';

type Page = 'dashboard' | 'complaints' | 'report' | 'notifications' | 'map' | 'feedback' | 'analytics' | 'performance' | 'manage' | 'profile';
const date = (value: string) => new Date(value.replace(' ', 'T') + (value.includes('Z') ? '' : 'Z')).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
const utcTime = (value: string) => new Date(value.replace(' ', 'T') + (value.includes('Z') ? '' : 'Z'));
const dateTime = (value: string) => utcTime(value).toLocaleString('en-GB', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' });
const closureState = (complaint: Complaint) => {
  if (!complaint.resolution_due_at || ['Rejected','Duplicate'].includes(complaint.status)) return null;
  if (['Closed','Citizen Verified','Finished'].includes(complaint.status)) return { label: complaint.closed_at && utcTime(complaint.closed_at) > utcTime(complaint.resolution_due_at) ? 'Confirmed late' : 'Confirmed on time', overdue: false };
  return Date.now() > utcTime(complaint.resolution_due_at).getTime()
    ? { label: `Closure overdue · ${dateTime(complaint.resolution_due_at)}`, overdue: true }
    : { label: `Target closure · ${dateTime(complaint.resolution_due_at)}`, overdue: false };
};
const roleName: Record<string, string> = { citizen: 'Citizen', staff: 'Department staff', admin: 'Administrator', superadmin: 'Super administrator' };
const severityClass = (severity: string) => severity.toLowerCase().replaceAll(' ', '-');

function Badge({ value, type = 'status' }: { value: string; type?: 'status' | 'severity' }) {
  return <span className={`badge ${type}-${severityClass(value)}`}>{value}</span>;
}
function SectionHeading({ eyebrow, title, right }: { eyebrow: string; title: string; right?: ReactNode }) {
  return <div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{right}</div>;
}
function Empty({ title, text }: { title: string; text: string }) {
  return <div className="empty"><CircleHelp size={27} /><strong>{title}</strong><p>{text}</p></div>;
}
function StatCard({ icon, label, value, foot, tone = 'mint' }: { icon: ReactNode; label: string; value: string | number; foot?: string; tone?: string }) {
  return <div className={`stat-card tone-${tone}`}><div className="stat-icon">{icon}</div><div className="stat-value">{value}</div><div className="stat-label">{label}</div>{foot && <div className="stat-foot">{foot}</div>}</div>;
}
function ComplaintList({ items, onOpen, compact = false }: { items: Complaint[]; onOpen: (id: number) => void; compact?: boolean }) {
  if (!items.length) return <Empty title="No issues here yet" text="Reports will appear as soon as they are submitted." />;
  return <div className="complaint-list">{items.map(c => <button className="complaint-row" key={c.id} onClick={() => onOpen(c.id)}>
    <span className={`row-icon ${severityClass(c.severity)}`}><MapPin size={18} /></span>
    <span className="row-main"><strong>{c.title}</strong><small>{c.code} <span>·</span> {c.area} <span>·</span> {c.category}</small><small className={closureState(c)?.overdue ? 'deadline-overdue' : 'deadline-muted'}>{closureState(c)?.label}{c.recurrence_flag && <> <span>·</span> Possible recurrence</>}</small></span>
    {!compact && <span className="row-date">{date(c.created_at)}</span>}
    <Badge value={c.status} /><ArrowRight size={16} className="row-arrow" />
  </button>)}</div>;
}
function Login({ onLogin, onRegister, onForgot, onRecoverCode, emailEnabled, turnstileSiteKey, busy, error }: { onLogin: (email: string, password: string) => Promise<void>; onRegister: (details: { name: string; email: string; area: string; password: string; turnstileToken?: string }) => Promise<void>; onForgot: (email: string) => Promise<boolean>; onRecoverCode: (code: string, password: string) => Promise<boolean>; emailEnabled: boolean; turnstileSiteKey: string | null; busy: boolean; error: string }) {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [name, setName] = useState('');
  const [area, setArea] = useState('');
  const [registering, setRegistering] = useState(false);
  const [recovering, setRecovering] = useState(false);
  const [recoverySent, setRecoverySent] = useState(false);
  const [usingCode, setUsingCode] = useState(false);
  const [recoveryCode, setRecoveryCode] = useState('');
  const [recoveryPassword, setRecoveryPassword] = useState('');
  const [codeRecovered, setCodeRecovered] = useState(false);
  const [turnstileToken, setTurnstileToken] = useState(''); const [challengeVersion, setChallengeVersion] = useState(0);
  if (usingCode) return <div className="setup-screen"><div className="setup-card"><div className="brand"><span className="brand-mark"><MapPin size={20} /></span><span>CivicPulse Dhaka</span></div><span className="eyebrow">ACCOUNT RECOVERY</span><h1>Use your recovery code</h1><p className="muted">Enter the private code you saved from Account security. It can be used only once.</p>{codeRecovered ? <p role="status">Password changed. Sign in with your new password.</p> : <form onSubmit={event => { event.preventDefault(); void onRecoverCode(recoveryCode.trim(), recoveryPassword).then(setCodeRecovered); }}><label>Recovery code<input value={recoveryCode} onChange={event => setRecoveryCode(event.target.value)} required /></label><label>New password<input type="password" value={recoveryPassword} onChange={event => setRecoveryPassword(event.target.value)} minLength={12} maxLength={128} required /></label>{error && <div className="error-box">{error}</div>}<button className="primary full" disabled={busy}>{busy ? 'Please wait…' : 'Reset password'}</button></form>}<button type="button" className="secondary" onClick={() => { setUsingCode(false); setRegistering(false); setRecovering(false); }}>Back to sign in</button></div></div>;
  return <div className="login-screen"><div className="login-left"><div className="brand"><span className="brand-mark"><MapPin size={20} /></span><span>CivicPulse</span></div>
    <div className="login-art"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><span className="art-pin pin-a"><MapPin /></span><span className="art-pin pin-b"><MapPin /></span><span className="art-pin pin-c"><MapPin /></span><span className="art-center"><Activity size={48} /></span></div>
    <div className="login-copy"><span className="eyebrow">A clearer view of Dhaka</span><h1>Every report moves Dhaka forward.</h1><p>Follow Dhaka city issues from first report to community-verified resolution.</p></div>
    <div className="login-proof"><span><Check size={16} /> Public issue map</span><span><Check size={16} /> Traceable progress</span><span><Check size={16} /> Community feedback</span></div>
  </div><div className="login-right"><div className="login-box"><span className="eyebrow">CIVIC ISSUE TRACKER</span><h2>{recovering ? 'Recover your account' : registering ? 'Join your community' : 'Welcome back'}</h2><p className="muted">{recovering ? 'Enter your email to request a password reset link.' : registering ? 'Create a citizen account to report issues and track progress.' : 'Sign in to report, manage, or review local issues.'}</p>
    <form onSubmit={e => { e.preventDefault(); if (recovering) void onForgot(email).then(setRecoverySent); else if (registering) void onRegister({ name, email, area, password, turnstileToken }).finally(() => { setTurnstileToken(''); setChallengeVersion(v => v + 1); }); else void onLogin(email,password); }}>
      {registering && <label>Full name<input value={name} onChange={e => setName(e.target.value)} minLength={2} maxLength={80} required /></label>}
      <label>Email address<input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label>
      {registering && <label>Your Dhaka neighborhood<input value={area} onChange={e => setArea(e.target.value)} minLength={2} maxLength={100} placeholder="e.g. Dhanmondi" required /></label>}
      {!recovering && <label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} minLength={registering ? 10 : undefined} required /></label>}
      {registering && <p className="muted">{emailEnabled ? 'We will email you a verification link. Verify before submitting a complaint.' : 'Email verification is not configured yet. Use an address you control.'}</p>}{registering && turnstileSiteKey && <TurnstileChallenge key={challengeVersion} siteKey={turnstileSiteKey} onToken={setTurnstileToken} />}{recoverySent && <p role="status">If this account exists, a reset link is on its way.</p>}{error && <div className="error-box">{error}</div>}<button className="primary full" disabled={busy || (registering && !!turnstileSiteKey && !turnstileToken)}>{busy ? 'Please wait…' : recovering ? 'Send reset link' : registering ? 'Create citizen account' : 'Sign in'} <ArrowRight size={17} /></button></form>
    <div className="login-links"><button type="button" onClick={() => { if (registering || recovering) { setRegistering(false); setRecovering(false); } else setRegistering(true); setPassword(''); }}>{registering || recovering ? 'Back to sign in' : 'New citizen? Create an account'}</button>{!registering && !recovering && emailEnabled && <button type="button" onClick={() => { setRecovering(true); setRecoverySent(false); }}>Forgot password?</button>}{!registering && !recovering && <button type="button" onClick={() => setUsingCode(true)}>Use recovery code</button>}</div>
    </div></div></div>;
}

function AccountLink({ purpose, token, onDone }: { purpose: 'verify' | 'reset'; token: string; onDone: () => void }) {
  const [password, setPassword] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [done, setDone] = useState(false);
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setBusy(true); setError('');
    try { await request(purpose === 'verify' ? 'verifyEmail' : 'resetPassword', { token, newPassword: password }); setDone(true); }
    catch (err) { setError(String(err instanceof Error ? err.message : err)); }
    finally { setBusy(false); }
  };
  return <div className="setup-screen"><div className="setup-card"><div className="brand"><span className="brand-mark"><MapPin size={20} /></span><span>CivicPulse Dhaka</span></div><span className="eyebrow">ACCOUNT SECURITY</span><h1>{purpose === 'verify' ? 'Verify your email' : 'Reset your password'}</h1>{done ? <p role="status">{purpose === 'verify' ? 'Email verified. You can now submit reports.' : 'Password changed. Sign in with your new password.'}</p> : <form onSubmit={event => void submit(event)}>{purpose === 'reset' && <label>New password<input type="password" value={password} onChange={event => setPassword(event.target.value)} minLength={12} maxLength={128} required /></label>}{error && <div className="error-box">{error}</div>}<button className="primary full" disabled={busy}>{busy ? 'Please wait…' : purpose === 'verify' ? 'Verify email' : 'Change password'}</button></form>}<button type="button" className="secondary" onClick={onDone}>Continue to CivicPulse</button></div></div>;
}

function OwnerSetup({ onSetup, busy, error }: { onSetup: (details: { key: string; name: string; email: string; password: string }) => Promise<void>; busy: boolean; error: string }) {
  const [key, setKey] = useState(''); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  return <div className="setup-screen"><div className="setup-card"><div className="brand"><span className="brand-mark"><MapPin size={20} /></span><span>CivicPulse Dhaka</span></div><span className="eyebrow">FIRST TIME SETUP</span><h1>Set up the Dhaka workspace</h1><p className="muted">The project owner creates the first administrator account. Keep the setup key private.</p><form onSubmit={e => { e.preventDefault(); void onSetup({ key, name, email, password }); }}><label>Setup key<input type="password" value={key} onChange={e => setKey(e.target.value)} required /></label><label>Your name<input value={name} onChange={e => setName(e.target.value)} minLength={3} required /></label><label>Your email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} minLength={12} required /></label>{error && <div className="error-box">{error}</div>}<button className="primary full" disabled={busy}>{busy ? 'Setting up…' : 'Create owner account'} <ArrowRight size={17} /></button></form></div></div>;
}

function AreaOverview({ userId }: { userId: number }) {
  const [query, setQuery] = useState('');
  const [summary, setSummary] = useState<AreaSummary | null>(null);
  const [error, setError] = useState('');
  useEffect(() => {
    let active = true;
    const load = () => {
      if (document.visibilityState !== 'visible') return;
      void request<AreaSummary>('areaSummary', { query }).then(result => { if (active) { setSummary(result); setError(''); } }).catch(() => { if (active) setError('Area totals could not be loaded.'); });
    };
    const initial = window.setTimeout(load, query ? 250 : 0);
    const timer = window.setInterval(load, 180000);
    window.addEventListener('focus', load);
    window.addEventListener('civic:refresh', load);
    return () => { active = false; window.clearTimeout(initial); window.clearInterval(timer); window.removeEventListener('focus', load); window.removeEventListener('civic:refresh', load); };
  }, [query, userId]);
  return <section className="card area-overview"><SectionHeading eyebrow="ALL DHAKA REPORTS" title="Complaints by area" right={<span className="count-pill">{summary?.cityTotal ?? '—'} citywide</span>} /><p className="muted">Search an area to see its total across all citizens and statuses. Individual reports are not shown here.</p><div className="search-box"><Search size={18} /><input aria-label="Search an area" placeholder="Search a Dhaka area, e.g. Dhanmondi" value={query} onChange={event => setQuery(event.target.value)} maxLength={80} /></div>{error && <p role="status">{error}</p>}<div className="area-grid"><div className="area-total"><span>{query ? `Matching “${query}”` : 'All Dhaka areas'}</span><strong>{summary?.total ?? '—'}</strong></div></div>{summary && query && summary.total === 0 && <p className="muted">No complaints found for this area.</p>}</section>;
}

function Dashboard({ data, onPage, onOpen }: { data: Snapshot; onPage: (page: Page) => void; onOpen: (id: number) => void }) {
  const { user, complaints, summary } = data;
  const own = complaints.filter(c => c.reporter_id === user.id);
  const assigned = complaints.filter(c => c.department_id === user.departmentId);
  const relevant = user.role === 'citizen' ? own : user.role === 'staff' ? assigned : complaints;
  const [recent, setRecent] = useState(relevant.slice(0, 5));
  useEffect(() => {
    let cancelled = false;
    const scope = user.role === 'citizen' ? 'My reports' : user.role === 'staff' ? 'Assigned to my department' : 'All issues';
    void request<PageResult<Complaint>>('listComplaints', { scope, limit: 5 }).then(result => { if (!cancelled) setRecent(result.complaints); }).catch(() => {});
    return () => { cancelled = true; };
  }, [user.id, user.role, summary.counts.total]);
  const highlights = user.role === 'citizen' ? [
    ['My reports', summary.own.total, <FileText size={20} />, 'mint'], ['Open issues', summary.own.open || 0, <Activity size={20} />, 'amber'],
    ['Resolved', summary.own.resolved || 0, <Check size={20} />, 'blue'],
    ['Awaiting review', summary.counts.pending || 0, <MapPin size={20} />, 'violet']
  ] as const : [
    ['Total reports', user.role === 'staff' ? summary.assigned?.total || 0 : summary.counts.total, <FileText size={20} />, 'mint'],
    ['Open issues', user.role === 'staff' ? summary.assigned?.open || 0 : summary.counts.open || 0, <Activity size={20} />, 'amber'],
    [user.role === 'staff' ? 'Completed' : 'Needs verification', user.role === 'staff' ? summary.assigned?.resolved || 0 : summary.counts.pending || 0, <ClipboardCheck size={20} />, 'blue'],
    ['Critical alerts', summary.counts.critical || 0, <Flag size={20} />, 'rose']
  ] as const;
  const categoryCounts = summary.categories.map(row => ({ name: data.categories.find(cat => cat.id === row.id)?.name || 'Other', count: row.count })).slice(0, 5);
  return <><div className="hero"><div><span className="eyebrow"><Sparkles size={14} /> DHAKA OPERATIONS, IN ONE PLACE</span><h1>Good {new Date().getHours() < 12 ? 'morning' : new Date().getHours() < 17 ? 'afternoon' : 'evening'}, {user.name.split(' ')[0]}.</h1><p>{user.role === 'citizen' ? 'Follow your own reports from submission through resolution.' : user.role === 'staff' ? 'Stay on top of assigned work and keep residents informed.' : 'Your Dhaka overview is ready. Review new reports and keep work moving.'}</p><div className="hero-actions"><button className="primary" onClick={() => onPage(user.role === 'citizen' ? 'report' : 'complaints')}>{user.role === 'citizen' ? <Plus size={18} /> : <ClipboardCheck size={18} />}{user.role === 'citizen' ? 'Report an issue' : 'Review complaints'}</button><button className="secondary" onClick={() => onPage('map')}><MapIcon size={18} /> {user.role === 'citizen' ? 'My report map' : 'Explore map'}</button></div></div><div className="hero-visual"><div className="visual-grid" /><span className="pulse-dot dot-one" /><span className="pulse-dot dot-two" /><span className="pulse-dot dot-three" /><div className="visual-label"><Activity size={17} /> Live Dhaka signal</div></div></div>
  <div className="stat-grid">{highlights.map(([label,value,icon,tone]) => <StatCard key={label} label={label} value={value} icon={icon} tone={tone} />)}</div>
  {['admin','superadmin'].includes(user.role) && <div className="deadline-strip"><span><Flag size={17} /> <strong>{summary.counts.overdue_closure || 0}</strong> overdue closure targets</span><span><Activity size={17} /> <strong>{summary.counts.recurring || 0}</strong> possible recurring issues</span>{user.role === 'superadmin' && <span><Check size={17} /> <strong>{summary.counts.citizen_verified || 0}</strong> waiting for Finished work</span>}<button className="text-button" onClick={() => onPage('complaints')}>Review cases <ArrowRight size={15} /></button></div>}
  <AreaOverview userId={user.id} />
  <div className="two-col"><div className="card"><SectionHeading eyebrow="RECENT ACTIVITY" title={user.role === 'citizen' ? 'Your reports' : 'Latest complaints'} right={<button className="text-button" onClick={() => onPage('complaints')}>View all <ArrowRight size={15} /></button>} /><ComplaintList items={recent} onOpen={onOpen} compact /></div>
  <div className="card"><SectionHeading eyebrow="DHAKA SNAPSHOT" title="Issues by category" right={<button className="text-button" onClick={() => onPage('analytics')}>Explore <ArrowRight size={15} /></button>} /><div className="bar-list">{categoryCounts.map((item,i) => <div className="bar-row" key={item.name}><span>{item.name}</span><div className="bar-track"><i style={{ width: `${Math.max(8,item.count/Math.max(1,categoryCounts[0].count)*100)}%`, background: ['#66dbc3','#82b7ff','#ffc883','#bca5ff','#ff9e9d'][i] }} /></div><strong>{item.count}</strong></div>)}</div><div className="insight-note"><MapPin size={17} /> {summary.counts.total} reports visible to your role.</div></div></div></>;
}

function Complaints({ data, onOpen }: { data: Snapshot; onOpen: (id: number) => void }) {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState('All statuses'); const [scope, setScope] = useState('All issues');
  const filterKey = `${query}\u0000${status}\u0000${scope}`; const filterRef = useRef(filterKey); filterRef.current = filterKey;
  const [page, setPage] = useState({ complaints: data.complaints, nextCursor: data.nextCursor, total: data.summary.counts.total });
  const [busy, setBusy] = useState(false);
  const scopes = data.user.role === 'citizen' ? ['My reports'] : data.user.role === 'staff' ? ['Assigned to my department','All issues'] : ['All issues','Citizen verified','Finished work','Overdue closure','Recurring issues','Needs verification','Awaiting feedback'];
  useEffect(() => setScope(scopes[0]), [data.user.role]);
  useEffect(() => {
    let cancelled = false;
    const timer = setTimeout(() => { void request<typeof page>('listComplaints', { query, scope, status }).then(result => { if (!cancelled) setPage(result); }).catch(() => {}); }, query ? 250 : 0);
    return () => { cancelled = true; clearTimeout(timer); };
  }, [query, scope, status, data.user.id, data.summary.counts.total, data.summary.counts.overdue_closure, data.summary.counts.recurring, data.summary.counts.closed, data.summary.counts.citizen_verified, data.summary.counts.pending, data.summary.feedback.count]);
  const loadMore = async () => {
    if (!page.nextCursor || busy) return;
    setBusy(true);
    try { const more = await request<typeof page>('listComplaints', { query, scope, status, cursor: page.nextCursor }); if (filterRef.current === filterKey) setPage(current => ({ complaints: [...current.complaints, ...more.complaints], nextCursor: more.nextCursor, total: more.total })); }
    finally { setBusy(false); }
  };
  return <><SectionHeading eyebrow="CASE MANAGEMENT" title="Complaints" right={<span className="count-pill">{page.total} reports</span>} /><div className="filter-card"><div className="search-box"><Search size={18} /><input placeholder="Search by title, ID, area, category…" value={query} onChange={e => setQuery(e.target.value)} /></div><div className="select-wrap"><Filter size={17} /><select value={scope} onChange={e => setScope(e.target.value)}>{scopes.map(x => <option key={x}>{x}</option>)}</select></div><div className="select-wrap"><ChevronDown size={17} /><select value={status} onChange={e => setStatus(e.target.value)}>{['All statuses','Submitted','Verified','Assigned','In Progress','Awaiting Feedback','Citizen Verified','Finished','Closed','Reopened','Rejected'].map(x => <option key={x}>{x}</option>)}</select></div></div><div className="card list-card"><ComplaintList items={page.complaints} onOpen={onOpen} /></div>{page.nextCursor && <button className="secondary load-more" disabled={busy} onClick={() => void loadMore()}>{busy ? 'Loading…' : `Load more (${page.complaints.length} of ${page.total})`}</button>}</>;
}

function readImage(file: File): Promise<string> {
  return new Promise((resolve,reject) => {
    if (!['image/png','image/jpeg','image/webp'].includes(file.type) || file.size > 2_000_000) return reject(new Error('Choose a PNG, JPEG or WebP image under 2 MB.'));
    const objectUrl = URL.createObjectURL(file);
    const image = new Image();
    image.onload = () => {
      URL.revokeObjectURL(objectUrl);
      for (const [limit, quality] of [[1200,.78],[960,.67],[760,.55]] as const) {
        const scale = Math.min(1, limit / Math.max(image.naturalWidth, image.naturalHeight));
        const canvas = document.createElement('canvas');
        canvas.width = Math.max(1, Math.round(image.naturalWidth * scale)); canvas.height = Math.max(1, Math.round(image.naturalHeight * scale));
        canvas.getContext('2d')?.drawImage(image, 0, 0, canvas.width, canvas.height);
        const result = canvas.toDataURL('image/webp', quality);
        if (result.length < 600000) return resolve(result);
      }
      reject(new Error('This image is too detailed. Choose a smaller photo.'));
    };
    image.onerror = () => { URL.revokeObjectURL(objectUrl); reject(new Error('Could not read image.')); };
    image.src = objectUrl;
  });
}

function Report({ data, onCreated, showError, turnstileSiteKey }: { data: Snapshot; onCreated: (id: number) => void; showError: (message: string) => void; turnstileSiteKey: string | null }) {
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [categoryId, setCategoryId] = useState(0);
  const [severity, setSeverity] = useState('Medium'); const [area, setArea] = useState(data.user.area || 'Dhanmondi');
  const [point, setPoint] = useState<{ latitude: number; longitude: number } | null>(null); const [image, setImage] = useState<string | null>(null);
  const [latitudeText, setLatitudeText] = useState(''); const [longitudeText, setLongitudeText] = useState('');
  const [nearby, setNearby] = useState<Array<{ id: number; code: string; title: string; status: string; distance: number }>>([]); const [busy, setBusy] = useState(false);
  const [turnstileToken, setTurnstileToken] = useState(''); const [challengeVersion, setChallengeVersion] = useState(0);
  const setCoordinates = (latitude: string, longitude: string) => {
    setLatitudeText(latitude); setLongitudeText(longitude);
    const lat = Number(latitude), lon = Number(longitude);
    setPoint(Boolean(latitude.trim() && longitude.trim()) && Number.isFinite(lat) && Number.isFinite(lon) && lat >= 23.68 && lat <= 23.92 && lon >= 90.30 && lon <= 90.53 ? { latitude: lat, longitude: lon } : null);
  };
  useEffect(() => { if (point && categoryId) void request<typeof nearby>('nearby', { ...point, categoryId }).then(setNearby).catch(() => setNearby([])); else setNearby([]); }, [point,categoryId]);
  const submit = async (event: FormEvent) => {
    event.preventDefault(); if (!point) return showError('Click the map to choose a location.');
    setBusy(true); try { const id = await request<number>('create', { title, description, categoryId, severity, area, ...point, image, turnstileToken }); onCreated(id); }
    catch (error) { showError(String(error instanceof Error ? error.message : error)); } finally { setBusy(false); setTurnstileToken(''); setChallengeVersion(v => v + 1); }
  };
  return <><SectionHeading eyebrow="HELP YOUR NEIGHBORHOOD" title="Report an issue" /><div className="report-layout"><form className="card report-form" onSubmit={submit}><div className="form-intro"><span className="step">01</span><div><h3>Tell us what happened</h3><p>A clear report helps the right team respond quickly.</p></div></div><div className="form-grid"><label className="wide">Issue title<input value={title} onChange={e => setTitle(e.target.value)} minLength={6} maxLength={120} placeholder="e.g. Large pothole near the main crossing" required /></label><label className="wide">Description<textarea value={description} onChange={e => setDescription(e.target.value)} minLength={12} rows={4} placeholder="Describe the problem and anything residents should know…" required /></label><label>Category<select value={categoryId} onChange={e => setCategoryId(Number(e.target.value))} required><option value={0}>Choose category</option>{data.categories.filter(c => c.active).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Severity<select value={severity} onChange={e => setSeverity(e.target.value)}>{['Low','Medium','High','Critical'].map(x => <option key={x}>{x}</option>)}</select></label><label className="wide">Dhaka neighborhood<input value={area} onChange={e => setArea(e.target.value)} required /></label></div>{categoryId > 0 && <p className="target-preview">Closure target for this category: {data.categories.find(c => c.id === categoryId)?.resolution_hours || 168} hours after submission. This is an internal target, not a guaranteed repair time.</p>}
    <div className="form-intro middle"><span className="step">02</span><div><h3>Pin the exact location</h3><p>Choose a point on the map, or enter coordinates using a keyboard.</p></div></div><LocationPicker value={point} onPick={(latitude, longitude) => setCoordinates(latitude.toFixed(5), longitude.toFixed(5))} /><div className="form-grid coordinate-inputs"><label>Latitude<input type="number" inputMode="decimal" step="any" min="23.68" max="23.92" value={latitudeText} onChange={e => setCoordinates(e.target.value, longitudeText)} placeholder="23.74690" /></label><label>Longitude<input type="number" inputMode="decimal" step="any" min="90.30" max="90.53" value={longitudeText} onChange={e => setCoordinates(latitudeText, e.target.value)} placeholder="90.37540" /></label></div><p className="coordinate" role="status">{point ? `Selected ${point.latitude.toFixed(5)}, ${point.longitude.toFixed(5)}` : 'Enter a point inside the Dhaka service area (23.68–23.92 N, 90.30–90.53 E).'}</p>
    {nearby.length > 0 && <div className="duplicate-warning"><strong>Similar reports nearby</strong><p>Someone may already have reported this issue. You can still submit a new report.</p>{nearby.map(item => <div key={item.id}>{item.code} · {item.title} · {item.distance} m · {item.status}</div>)}</div>}
    <div className="form-intro middle"><span className="step">03</span><div><h3>Add evidence</h3><p>One photo helps the team identify the issue.</p></div></div><label className="upload-box"><Upload size={22} /><strong>{image ? 'Photo attached' : 'Choose a photo'}</strong><small>PNG, JPEG or WebP · maximum 2 MB</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e => { try { setImage(e.target.files?.[0] ? await readImage(e.target.files[0]) : null); } catch (err) { showError(String(err)); } }} /></label>{image && <img className="preview-image" src={image} alt="Complaint evidence preview" />}
    {turnstileSiteKey && <TurnstileChallenge key={challengeVersion} siteKey={turnstileSiteKey} onToken={setTurnstileToken} />}<button className="primary submit-report" disabled={busy || (!!turnstileSiteKey && !turnstileToken)}>{busy ? 'Submitting…' : 'Submit complaint'} <ArrowRight size={18} /></button></form><aside className="report-aside"><div className="card aside-card"><div className="aside-icon"><ShieldCheck size={23} /></div><h3>What happens next?</h3><div className="mini-timeline"><span>1</span><p>An administrator verifies your report.</p><span>2</span><p>The responsible department receives it.</p><span>3</span><p>You can follow updates and review completed work.</p></div></div><div className="aside-tip"><MapPin size={19} /><p>Your report appears on the Dhaka issue map after administrator verification. Its public location is approximate. Avoid personal details in the title and photos.</p></div></aside></div></>;
}

function MapPage({ data, onOpen }: { data: Snapshot; onOpen: (id: number) => void }) {
  const [mode, setMode] = useState<'markers' | 'heat'>('markers'); const [category, setCategory] = useState('All categories'); const [status, setStatus] = useState('All statuses');
  const [page, setPage] = useState({ complaints: data.complaints, nextCursor: data.nextCursor, total: data.summary.counts.total });
  const [busy, setBusy] = useState(false);
  const filtered = page.complaints.filter(c => (category === 'All categories' || c.category === category) && (status === 'All statuses' || c.status === status));
  const loadMore = async () => { if (!page.nextCursor || busy) return; setBusy(true); try { const more = await request<typeof page>('listComplaints', { cursor: page.nextCursor }); setPage(current => ({ complaints: [...current.complaints, ...more.complaints], nextCursor: more.nextCursor, total: more.total })); } finally { setBusy(false); } };
  return <><SectionHeading eyebrow="GEOGRAPHIC INTELLIGENCE" title="Explore Dhaka" right={<span className="count-pill"><MapPin size={15} /> Dhaka, Bangladesh</span>} /><div className="map-toolbar"><div className="segmented"><button className={mode === 'markers' ? 'active' : ''} onClick={() => setMode('markers')}><MapPin size={16} /> Issue map</button><button className={mode === 'heat' ? 'active' : ''} onClick={() => setMode('heat')}><Activity size={16} /> Density view</button></div><div className="map-filters"><select value={category} onChange={e => setCategory(e.target.value)}><option>All categories</option>{data.categories.map(c => <option key={c.id}>{c.name}</option>)}</select><select value={status} onChange={e => setStatus(e.target.value)}>{['All statuses','Submitted','Assigned','In Progress','Awaiting Feedback','Citizen Verified','Finished','Closed','Reopened'].map(x => <option key={x}>{x}</option>)}</select></div></div><IssueMap complaints={filtered} mode={mode} onOpen={onOpen} /><p className="method-note">Showing {page.complaints.length} of {page.total} reports. Filters apply to loaded map points.</p>{page.nextCursor && <button className="secondary load-more" disabled={busy} onClick={() => void loadMore()}>{busy ? 'Loading…' : 'Load more map points'}</button>}<div className="map-bottom"><div className="card map-legend"><strong>Issue types</strong><span><i style={{background:'#f59e6c'}} /> Roads</span><span><i style={{background:'#b19aff'}} /> Waste</span><span><i style={{background:'#66b8ff'}} /> Water & drainage</span><span><i style={{background:'#ffd277'}} /> Lighting</span></div><div className="card map-summary"><strong>{filtered.length} loaded complaints</strong><span>{new Set(filtered.map(c => c.area)).size} affected areas</span><span>{filtered.filter(c => !['Closed','Citizen Verified','Finished'].includes(c.status)).length} still open</span></div></div></>;
}

function FeedbackPage({ data, onOpen }: { data: Snapshot; onOpen: (id: number) => void }) {
  const awaiting = data.complaints.filter(c => c.status === 'Awaiting Feedback');
  const reviews = data.feedback.slice(0, 6);
  return <><SectionHeading eyebrow="COMMUNITY VOICE" title="Resolution feedback" /><div className="stat-grid three"><StatCard icon={<MessageSquare size={20} />} label="Community responses" value={data.summary.feedback.count} tone="mint" /><StatCard icon={<Check size={20} />} label="Awaiting review" value={data.summary.counts.awaiting || 0} tone="blue" /><StatCard icon={<Activity size={20} />} label="Average rating" value={data.summary.feedback.average !== null ? `${data.summary.feedback.average.toFixed(1)}/5` : '—'} tone="amber" /></div><div className="two-col"><div className="card"><SectionHeading eyebrow="READY FOR YOUR VOICE" title="Recent completed work" /><ComplaintList items={awaiting} onOpen={onOpen} compact /></div><div className="card"><SectionHeading eyebrow="LATEST RESPONSES" title="What residents said" />{reviews.length ? <div className="review-list">{reviews.map(f => { const c = data.complaints.find(x => x.id === f.complaint_id); return <button key={f.id} onClick={() => c && onOpen(c.id)}><span className="review-avatar">{f.author[0]}</span><span><strong>{f.author} <em>{'★'.repeat(f.rating)}{'☆'.repeat(5-f.rating)}</em></strong><small>{c?.title} · {f.local ? 'Area matched resident' : 'Public feedback'}</small><p>{f.comment || `Issue ${f.resolution.toLowerCase()} resolved.`}</p></span></button>; })}</div> : <Empty title="No feedback yet" text="Residents can review issues after work is completed." />}</div></div><p className="method-note">The list shows feedback for recent reports. Totals include all reports visible to your role.</p></>;
}

function Analytics({ data }: { data: Snapshot }) {
  const { summary } = data;
  const categoryRows = summary.categories.map(row => ({ name: data.categories.find(c => c.id === row.id)?.name || 'Other', count: row.count }));
  const departments = summary.departments.map(row => ({ name: data.departments.find(d => d.id === row.id)?.name || 'Department', ...row }));
  return <><SectionHeading eyebrow="OPERATIONAL INSIGHTS" title="Dhaka analytics" /><div className="stat-grid"><StatCard icon={<FileText size={20} />} label="Total reports" value={summary.counts.total} tone="mint" /><StatCard icon={<Activity size={20} />} label="Still open" value={summary.counts.open || 0} tone="amber" /><StatCard icon={<Check size={20} />} label="Finished / legacy closed" value={summary.counts.closed || 0} tone="blue" /><StatCard icon={<Flag size={20} />} label="Repair cycles reopened" value={summary.reopened} tone="rose" /></div>
    <div className="two-col"><div className="card"><SectionHeading eyebrow="ISSUE MIX" title="Reports by category" /><div className="bar-list tall">{categoryRows.map((item,i) => <div className="bar-row" key={item.name}><span>{item.name}</span><div className="bar-track"><i style={{ width: `${item.count/Math.max(1,categoryRows[0].count)*100}%`, background: ['#66dbc3','#82b7ff','#ffc883','#bca5ff','#ff9e9d'][i%5] }} /></div><strong>{item.count}</strong></div>)}</div></div>
    <div className="card"><SectionHeading eyebrow="GEOGRAPHIC PATTERN" title="Areas needing attention" /><div className="area-list">{summary.areas.map((row,i) => <div key={row.area}><span className="rank">{String(i+1).padStart(2,'0')}</span><span><strong>{row.area}</strong><small>{row.open} open issues</small></span><b>{row.count}</b></div>)}</div></div></div>
    <div className="card"><SectionHeading eyebrow="SERVICE DELIVERY" title="Department performance" /><div className="performance-grid">{departments.map(d => <div className="performance-card" key={d.id}><span className="dept-icon"><Users size={18} /></span><h3>{d.name}</h3><div><strong>{d.count}</strong><small>assigned</small></div><div><strong>{d.resolved}</strong><small>completed</small></div></div>)}</div></div><p className="method-note">Counts use all reports visible to your role. Area and department lists show the top 20. Area matched feedback remains provisional until addresses are independently verified.</p></>;
}

function NotificationsPage({ data, onOpen, refresh, showError }: { data: Snapshot; onOpen: (id: number) => void; refresh: () => Promise<void>; showError: (message: string) => void }) {
  const openNotification = async (id: number, complaintId: number) => {
    try { await request('readNotification', { id }); await refresh(); onOpen(complaintId); }
    catch (error) { showError(String(error instanceof Error ? error.message : error)); }
  };
  return <><SectionHeading eyebrow="YOUR UPDATES" title="Notifications" right={<span className="count-pill">{data.notifications.filter(item => !item.read_at).length} unread</span>} />
    <div className="card notification-list">{data.notifications.length ? data.notifications.map(item => <button key={item.id} className={`notification-item ${item.read_at ? '' : 'unread'}`} onClick={() => void openNotification(item.id, item.complaint_id)}><span className="notification-icon"><Bell size={18} /></span><span><strong>{item.title}</strong><small>{item.message}</small><time>{dateTime(item.created_at)}</time></span><ArrowRight size={16} /></button>) : <Empty title="No notifications yet" text="Case updates and deadline alerts will appear here." />}</div></>;
}

function PerformancePage({ data, onPage, onOpen, showError }: { data: Snapshot; onPage: (page: Page) => void; onOpen: (id: number) => void; showError: (message: string) => void }) {
  const [report, setReport] = useState<Performance | null>(null);
  const [departmentId, setDepartmentId] = useState('all');
  useEffect(() => { let active = true; void request<Performance>('performance').then(value => { if (active) setReport(value); }).catch(error => showError(String(error))); return () => { active = false; }; }, [data.summary.counts.finished, data.summary.counts.citizen_verified, data.summary.feedback.count]);
  const areas = (report?.areas || []).filter(row => departmentId === 'all' || row.department_id === Number(departmentId));
  const top = Math.max(1, ...areas.map(row => row.finished));
  return <><SectionHeading eyebrow="SUPER ADMIN REVIEW" title="Finished work performance" /><p className="muted">Only citizen-confirmed repairs count. Ratings use the latest confirmation for each finished case.</p>
    <div className="stat-grid three"><StatCard icon={<Check size={20} />} label="Finished cases" value={report?.departments.reduce((sum,row) => sum + row.finished,0) ?? '—'} tone="mint" /><StatCard icon={<Bell size={20} />} label="Waiting for your review" value={data.summary.counts.citizen_verified || 0} tone="amber" /><StatCard icon={<Users size={20} />} label="Departments" value={report?.departments.length ?? '—'} tone="blue" /></div>
    {(data.summary.counts.citizen_verified || 0) > 0 && <div className="deadline-strip"><span><Check size={17} /> <strong>{data.summary.counts.citizen_verified}</strong> citizen verified case(s) await Finished work</span><button className="text-button" onClick={() => onPage('complaints')}>Open complaints <ArrowRight size={15} /></button></div>}
    {!!report?.pendingReopenRequests.length && <div className="card"><SectionHeading eyebrow="REWORK" title="Requests awaiting a decision" /><div className="complaint-list">{report.pendingReopenRequests.map(item => <button className="complaint-row" key={item.id} onClick={() => onOpen(item.complaint_id)}><span className="row-main"><strong>{item.code} · {item.title}</strong><small>{item.reason}</small></span><ArrowRight size={16} /></button>)}</div></div>}
    <div className="card"><SectionHeading eyebrow="CITIZEN RATINGS" title="Department scorecard" /><p className="muted">Rates use finished, citizen-confirmed cases. Time is from report submission to citizen confirmation; rating count includes confirmed ratings.</p><div className="performance-grid">{report?.departments.map(row => <div className="performance-card" key={row.id}><span className="dept-icon"><Users size={18} /></span><h3>{row.name}</h3><div><strong>{row.average_rating === null ? '—' : `${row.average_rating.toFixed(1)} ★`}</strong><small>{row.rating_count} ratings</small></div><div><strong>{row.finished}</strong><small>finished · {row.awaiting_finish} awaiting review</small></div><div><strong>{row.median_confirmation_hours === null ? '—' : `${row.median_confirmation_hours} h`}</strong><small>median to citizen confirmation</small></div><div><strong>{row.on_time_percent === null ? '—' : `${row.on_time_percent}%`}</strong><small>confirmed by deadline · {row.sample_count} cases</small></div><div><strong>{row.reopened_percent === null ? '—' : `${row.reopened_percent}%`}</strong><small>reopened after a repair</small></div></div>)}</div></div>
    <div className="card"><SectionHeading eyebrow="AREA OUTPUT" title="Accomplished work by area" right={<select aria-label="Filter department" value={departmentId} onChange={event => setDepartmentId(event.target.value)}><option value="all">All departments</option>{report?.departments.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select>} />{areas.length ? <div className="area-performance-chart">{areas.map(row => <div className="area-performance-row" key={`${row.department_id}:${row.area}`}><div><strong>{row.area}</strong><small>{row.department} · {row.average_rating?.toFixed(1)} ★</small></div><div className="bar-track"><i style={{width: `${row.finished / top * 100}%`}} /></div><b>{row.finished}</b></div>)}</div> : <Empty title="No finished work yet" text="The graph will fill after citizens verify repairs and you move them to Finished work." />}</div></>;
}

function Profile({ user, showError, emailEnabled, pushPublicKey }: { user: User; showError: (message: string) => void; emailEnabled: boolean; pushPublicKey: string | null }) {
  const [currentPassword, setCurrentPassword] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [busy, setBusy] = useState(false);
  const [saved, setSaved] = useState(false);
  const [verificationSent, setVerificationSent] = useState(false);
  const [recoveryPassword, setRecoveryPassword] = useState('');
  const [recoveryCode, setRecoveryCode] = useState('');
  const [pushStatus, setPushStatus] = useState('');
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setBusy(true); setSaved(false);
    try { await request('changePassword', { currentPassword, newPassword }); setCurrentPassword(''); setNewPassword(''); setRecoveryCode(''); setSaved(true); }
    catch (error) { showError(String(error instanceof Error ? error.message : error)); }
    finally { setBusy(false); }
  };
  const resend = async () => { setBusy(true); try { await request('requestVerification'); setVerificationSent(true); } catch (error) { showError(String(error instanceof Error ? error.message : error)); } finally { setBusy(false); } };
  const generateCode = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setRecoveryCode(''); try { setRecoveryCode(await request<string>('issueRecoveryCode', { password: recoveryPassword })); setRecoveryPassword(''); } catch (error) { showError(String(error instanceof Error ? error.message : error)); } finally { setBusy(false); } };
  const turnOnAlerts = async () => { if (!pushPublicKey) return; setBusy(true); try { const status = await enablePush(pushPublicKey); setPushStatus(status === 'enabled' ? 'Browser alerts enabled on this device.' : status === 'denied' ? 'Browser notification permission was declined. Change it in browser settings.' : 'This browser does not support background alerts.'); } catch (error) { showError(String(error instanceof Error ? error.message : error)); } finally { setBusy(false); } };
  const turnOffAlerts = async () => { setBusy(true); try { await disablePush(); setPushStatus('Browser alerts disabled on this device.'); } catch (error) { showError(String(error instanceof Error ? error.message : error)); } finally { setBusy(false); } };
  return <><SectionHeading eyebrow="YOUR ACCOUNT" title="Account security" /><div className="card profile-security"><h3>{user.name}</h3><p>{user.email} · {roleName[user.role]}</p><p>Email: {user.emailVerified ? 'verified' : emailEnabled ? 'verification needed' : 'verification not available yet'}</p>{!user.emailVerified && emailEnabled && <><button type="button" className="secondary" disabled={busy} onClick={() => void resend()}>Send verification link</button>{verificationSent && <p role="status">Verification link sent. Check your email, then click Refresh here.</p>}</>}<form className="account-form" onSubmit={submit}><label>Current password<input type="password" value={currentPassword} onChange={event => setCurrentPassword(event.target.value)} required /></label><label>New password<input type="password" value={newPassword} onChange={event => setNewPassword(event.target.value)} minLength={12} maxLength={128} required /></label><button className="primary" disabled={busy}>{busy ? 'Saving…' : 'Change password'}</button></form>{saved && <p role="status">Password updated. Other signed-in devices have been signed out.</p>}</div>{pushPublicKey && pushAvailable() && <div className="card profile-security"><h3>Browser alerts</h3><p className="muted">Receive case updates even when this tab is closed. Your browser will ask for permission once.</p><div className="action-row"><button type="button" className="primary" disabled={busy} onClick={() => void turnOnAlerts()}>Enable alerts</button><button type="button" className="secondary" disabled={busy} onClick={() => void turnOffAlerts()}>Disable on this device</button></div>{pushStatus && <p role="status">{pushStatus}</p>}</div>}<div className="card profile-security"><h3>Recovery code</h3><p className="muted">Generate a one-time code while you can sign in. Save it privately outside this laptop. A new code replaces the previous one and expires after one year.</p><form className="account-form" onSubmit={generateCode}><label>Current password<input type="password" value={recoveryPassword} onChange={event => setRecoveryPassword(event.target.value)} required /></label><button className="secondary" disabled={busy}>Generate new recovery code</button></form>{recoveryCode && <div role="status"><p>Save this code now. It will not be shown again:</p><code className="recovery-code">{recoveryCode}</code></div>}</div></>;
}

function Manage({ data, refresh, showError, backupEnabled }: { data: Snapshot; refresh: () => Promise<void>; showError: (message: string) => void; backupEnabled: boolean }) {
  const [kind, setKind] = useState<'department' | 'category'>('category');
  const [name, setName] = useState(''); const [departmentId, setDepartmentId] = useState('');
  const [accountName, setAccountName] = useState(''); const [accountEmail, setAccountEmail] = useState('');
  const [accountPassword, setAccountPassword] = useState(''); const [accountRole, setAccountRole] = useState<'staff' | 'admin'>('staff');
  const [accountDepartment, setAccountDepartment] = useState(''); const [busy, setBusy] = useState(false);
  const [managementStatus, setManagementStatus] = useState('');
  const [targetCategoryId, setTargetCategoryId] = useState('');
  const [targetHours, setTargetHours] = useState('168');
  const [targetStatus, setTargetStatus] = useState('');
  const [backupPassword, setBackupPassword] = useState('');
  const [backupPassphrase, setBackupPassphrase] = useState('');
  const [backupStatus, setBackupStatus] = useState('');
  const [backupBusy, setBackupBusy] = useState(false);
  const saveBackup = async (event: FormEvent) => {
    event.preventDefault(); setBackupBusy(true); setBackupStatus('Starting backup…');
    try { await downloadEncryptedBackup(backupPassword, backupPassphrase, setBackupStatus); setBackupPassword(''); setBackupPassphrase(''); }
    catch (error) { setBackupStatus(''); showError(String(error instanceof Error ? error.message : error)); }
    finally { setBackupBusy(false); }
  };
  const add = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setManagementStatus(''); try { await request('manage', { type: kind, name, departmentId: departmentId || null }); setName(''); await refresh(); setManagementStatus(kind === 'department' ? 'Department created. Add a category assigned to it so citizens can choose that service.' : 'Category created and available for new reports.'); } catch (error) { showError(String(error instanceof Error ? error.message : error)); } finally { setBusy(false); } };
  const addAccount = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await request('manage', { type: 'user', name: accountName, email: accountEmail, password: accountPassword, role: accountRole, departmentId: accountDepartment || null }); setAccountName(''); setAccountEmail(''); setAccountPassword(''); await refresh(); } catch (error) { showError(String(error instanceof Error ? error.message : error)); } finally { setBusy(false); } };
  const saveTarget = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setTargetStatus(''); try { await request('manage', { type: 'resolutionTime', categoryId: Number(targetCategoryId), hours: Number(targetHours) }); await refresh(); setTargetStatus('Closure target saved. It applies to new reports only.'); } catch (error) { showError(String(error instanceof Error ? error.message : error)); } finally { setBusy(false); } };
  const changeAccount = async (account: User) => { setBusy(true); try { await request('manage', { type: 'userStatus', userId: account.id, active: !account.active }); await refresh(); } catch (error) { showError(String(error instanceof Error ? error.message : error)); } finally { setBusy(false); } };
  return <><SectionHeading eyebrow="PLATFORM CONTROL" title="Administration" />
    <div className="stat-grid three"><StatCard icon={<Users size={20} />} label="Accounts" value={data.users.length} tone="mint" /><StatCard icon={<Settings size={20} />} label="Categories" value={data.categories.length} tone="blue" /><StatCard icon={<ShieldCheck size={20} />} label="Audit events" value={data.audit.length} tone="amber" /></div>
    <div className="two-col"><div className="card"><SectionHeading eyebrow="STRUCTURE" title="Categories & departments" /><form className="management-form" onSubmit={add}><select value={kind} onChange={e => setKind(e.target.value as 'category' | 'department')}><option value="category">New category</option><option value="department">New department</option></select><input value={name} onChange={e => setName(e.target.value)} placeholder="Name" minLength={3} required />{kind === 'category' && <select value={departmentId} onChange={e => setDepartmentId(e.target.value)}><option value="">No default department</option>{data.departments.filter(d => d.active).map(d => <option value={d.id} key={d.id}>{d.name}</option>)}</select>}<button className="primary" disabled={busy}><Plus size={16} /> Add</button></form>{managementStatus && <p role="status">{managementStatus}</p>}<h3>Departments</h3><div className="settings-list">{data.departments.map(d => <div key={d.id}><strong>{d.name}</strong><span>{data.categories.filter(c => c.department_id === d.id).length} categories · {d.active ? 'Active' : 'Inactive'}</span></div>)}</div><h3>Report categories</h3><p className="muted">Citizens select a category. Assign categories to departments to route new reports.</p><div className="settings-list">{data.categories.map(c => <div key={c.id}><strong>{c.name}</strong><span>{data.departments.find(d => d.id === c.department_id)?.name || 'Unassigned'}</span></div>)}</div></div>
    <div className="card"><SectionHeading eyebrow="ACCESS" title="Team accounts" /><form className="account-form" onSubmit={addAccount}><input value={accountName} onChange={e => setAccountName(e.target.value)} placeholder="Full name" minLength={3} required /><input value={accountEmail} onChange={e => setAccountEmail(e.target.value)} type="email" placeholder="Work email" required /><input value={accountPassword} onChange={e => setAccountPassword(e.target.value)} type="password" minLength={10} placeholder="Temporary password (10+ characters)" required /><select value={accountRole} onChange={e => setAccountRole(e.target.value as 'staff' | 'admin')}><option value="staff">Department staff</option><option value="admin">Administrator</option></select>{accountRole === 'staff' && <select value={accountDepartment} onChange={e => setAccountDepartment(e.target.value)} required><option value="">Choose department</option>{data.departments.filter(d => d.active).map(d => <option value={d.id} key={d.id}>{d.name}</option>)}</select>}<button className="primary" disabled={busy}><Plus size={16} /> Add account</button></form><div className="settings-list">{data.users.map(u => <div key={u.id}><strong>{u.name}</strong><span>{roleName[u.role]} · {u.department_id ? data.departments.find(d => d.id === u.department_id)?.name + ' · ' : ''}{u.email}</span></div>)}</div></div></div>
    <div className="card"><SectionHeading eyebrow="SERVICE TARGETS" title="Closure deadlines by category" /><p className="muted">New complaints receive the selected category’s target. Changing a target does not rewrite deadlines already given to residents.</p><form className="target-form" onSubmit={saveTarget}><label>Category<select value={targetCategoryId} onChange={e => { setTargetCategoryId(e.target.value); setTargetHours(String(data.categories.find(c => c.id === Number(e.target.value))?.resolution_hours || 168)); }} required><option value="">Choose category</option>{data.categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Hours to closure<input type="number" min="1" max="720" step="1" value={targetHours} onChange={e => setTargetHours(e.target.value)} required /></label><button className="primary" disabled={busy}>Save target</button></form>{targetStatus && <p role="status">{targetStatus}</p>}<div className="target-grid">{data.categories.map(c => <span key={c.id}><strong>{c.name}</strong>{c.resolution_hours} hours</span>)}</div></div>
    <div className="card"><SectionHeading eyebrow="ACCESS CONTROL" title="Manage staff access" /><div className="settings-list">{data.users.filter(u => ['admin','staff'].includes(u.role)).map(u => <div key={u.id}><strong>{u.name} · {roleName[u.role]}</strong><span>{u.email} · {u.active ? 'Active' : 'Disabled'}</span><button type="button" className="account-toggle" disabled={busy} onClick={() => void changeAccount(u)}>{u.active ? 'Disable access' : 'Reactivate access'}</button></div>)}</div></div>
    <div className="card"><SectionHeading eyebrow="DATA RECOVERY" title="Encrypted owner backup" /><p role="status">Scheduled offsite backup: {backupEnabled ? 'configured; check the private bucket for successful daily files' : 'not configured. Keep downloading manual encrypted backups.'}</p><p className="muted">Download a protected copy of accounts, reports, images, feedback, and audit records. Keep the backup passphrase in a separate safe place. This export can use significant browser memory as records grow.</p><form className="account-form" onSubmit={saveBackup}><label>Your current password<input type="password" autoComplete="current-password" value={backupPassword} onChange={e => setBackupPassword(e.target.value)} required /></label><label>Backup passphrase (16+ characters)<input type="password" autoComplete="new-password" minLength={16} value={backupPassphrase} onChange={e => setBackupPassphrase(e.target.value)} required /></label><button className="primary" disabled={backupBusy}><Download size={16} /> {backupBusy ? 'Preparing…' : 'Download encrypted backup'}</button></form>{backupStatus && <p role="status">{backupStatus}</p>}</div>
    <div className="card"><SectionHeading eyebrow="ACCOUNTABILITY" title="Recent audit trail" /><div className="audit-list">{data.audit.slice(0, 12).map(a => <div key={a.id}><span className="audit-dot" /><span><strong>{a.actor}</strong> {a.action.toLowerCase()} {a.target_type} #{a.target_id}<small>{a.detail || '—'}</small></span><time>{date(a.created_at)}</time></div>)}</div></div></>;
}

function Detail({ data, complaint, recurrence, escalationEvents, reopenRequests, onClose, refresh, showError }: { data: Snapshot; complaint: Complaint; recurrence: ComplaintDetail['recurrence']; escalationEvents: ComplaintDetail['escalationEvents']; reopenRequests: ComplaintDetail['reopenRequests']; onClose: () => void; refresh: () => Promise<void>; showError: (message: string) => void }) {
  const [note, setNote] = useState(''); const [departmentId, setDepartmentId] = useState(complaint.department_id ? String(complaint.department_id) : ''); const [priority, setPriority] = useState(complaint.priority);
  const [rating, setRating] = useState(5); const [resolution, setResolution] = useState('Yes'); const [comment, setComment] = useState(''); const [completionImage, setCompletionImage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const [reworkReason, setReworkReason] = useState('');
  const [nearby, setNearby] = useState<Array<{ id: number; code: string; title: string; distance: number }>>([]); const [duplicateId, setDuplicateId] = useState('');
  useEffect(() => { void request<typeof nearby>('nearby', { latitude: complaint.latitude, longitude: complaint.longitude, categoryId: complaint.category_id }).then(rows => setNearby(rows.filter(row => row.id !== complaint.id))).catch(() => setNearby([])); }, [complaint.id,complaint.category_id,complaint.latitude,complaint.longitude]);
  const updates = data.updates.filter(u => u.complaint_id === complaint.id);
  const cycles = data.cycles.filter(c => c.complaint_id === complaint.id);
  const latestCycle = cycles[0];
  const reviews = data.feedback.filter(f => f.complaint_id === complaint.id);
  const currentReviews = reviews.filter(f => f.cycle_id === latestCycle?.id);
  const average = currentReviews.length ? currentReviews.reduce((s,f) => s + f.rating,0)/currentReviews.length : null;
  const notResolved = currentReviews.length ? currentReviews.filter(f => f.resolution === 'No').length/currentReviews.length*100 : 0;
  const flagged = average !== null && (average < 3 || notResolved > 40);
  const canFeedback = data.user.role === 'citizen' && complaint.status === 'Awaiting Feedback' && !currentReviews.some(f => f.user_id === data.user.id);
  const perform = async (action: string, extra: Record<string, unknown> = {}) => { setBusy(true); try { await request('action', { id: complaint.id, action, note, ...extra }); setNote(''); setCompletionImage(null); await refresh(); } catch (error) { showError(String(error instanceof Error ? error.message : error)); } finally { setBusy(false); } };
  const sendFeedback = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await request('feedback', { id: complaint.id, rating, resolution, comment }); setComment(''); await refresh(); } catch (error) { showError(String(error instanceof Error ? error.message : error)); } finally { setBusy(false); } };
  const askRework = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await request('requestReopen', { id: complaint.id, reason: reworkReason }); setReworkReason(''); await refresh(); } catch (error) { showError(String(error instanceof Error ? error.message : error)); } finally { setBusy(false); } };
  const decideRework = async (requestId: number, decision: 'Approved' | 'Declined') => { setBusy(true); try { await request('decideReopen', { requestId, decision, note }); setNote(''); await refresh(); } catch (error) { showError(String(error instanceof Error ? error.message : error)); } finally { setBusy(false); } };
  const admin = ['admin','superadmin'].includes(data.user.role); const staff = data.user.role === 'staff' && complaint.department_id === data.user.departmentId;
  return <div className="drawer-backdrop" onClick={onClose}><aside className="detail-drawer" role="dialog" aria-modal="true" aria-label={`${complaint.code} issue details`} onKeyDown={e => { if (e.key === 'Escape') onClose(); }} onClick={e => e.stopPropagation()}><div className="drawer-top"><div><span className="eyebrow">CASE {complaint.code}</span><h2>Issue details</h2></div><div className="drawer-actions"><button type="button" className="icon-button" disabled={busy} onClick={() => { setBusy(true); void refresh().catch(error => showError(String(error))).finally(() => setBusy(false)); }} aria-label="Refresh case" title="Refresh case"><Activity size={18} /></button><button className="icon-button" onClick={onClose} aria-label="Close details"><X size={20} /></button></div></div><div className="drawer-body"><div className="detail-heading"><div className="detail-icon"><MapPin size={24} /></div><h3>{complaint.title}</h3><p>{complaint.description}</p><div className="badge-row"><Badge value={complaint.status} /><Badge value={complaint.severity} type="severity" /></div></div>
    <div className="detail-grid"><div><small>AREA</small><strong>{complaint.area}</strong></div><div><small>CATEGORY</small><strong>{complaint.category}</strong></div><div><small>DEPARTMENT</small><strong>{complaint.department || 'Not assigned'}</strong></div><div><small>PRIORITY</small><strong>{complaint.priority}</strong></div><div><small>REPORTED</small><strong>{date(complaint.created_at)}</strong></div><div><small>LOCATION</small><strong>{complaint.latitude.toFixed(4)}, {complaint.longitude.toFixed(4)}</strong></div></div>
    <div className={`detail-section closure-panel ${closureState(complaint)?.overdue ? 'is-overdue' : ''}`}><h4>Closure target</h4><strong>{closureState(complaint)?.label || 'Not applicable to this case status'}</strong>{complaint.resolution_due_at && !['Rejected','Duplicate'].includes(complaint.status) && <p>Target: {dateTime(complaint.resolution_due_at)}. The target stops when the citizen confirms the completed repair. The super administrator then files it as Finished work.</p>}</div>
    {complaint.recurrence_flag && <div className="detail-section recurrence-panel"><h4>Possible recurring issue</h4><p>A closed issue in the same category was reported within 100 metres and closed in the past 90 days. This flag needs human review; it does not mark this report as a duplicate.</p>{recurrence && <p><strong>{recurrence.code}</strong> · {recurrence.title} · {recurrence.closed_at ? `closed ${date(recurrence.closed_at)}` : 'reopened after the repeat report'}</p>}</div>}
    {complaint.image && <div className="detail-section"><h4>Report evidence</h4><img src={complaint.image} alt="Citizen submitted evidence" /></div>}{complaint.completion_image && <div className="detail-section"><h4>Completion evidence</h4><img src={complaint.completion_image} alt="Department completion evidence" /></div>}
    {cycles.length > 0 && <div className="detail-section"><h4>Repair evidence by cycle</h4>{cycles.map(c => <div className="repair-evidence" key={c.id}><strong>Cycle {c.number} · {c.reopened_at ? 'Reopened' : c.closed_at ? 'Citizen confirmed' : 'Feedback open'}</strong><small>Completed {dateTime(c.resolved_at)}</small>{c.completion_note && <p>{c.completion_note}</p>}{c.completion_image && <img src={c.completion_image} alt={`Department repair photo, cycle ${c.number}`} />}</div>)}</div>}
    {latestCycle && <div className="detail-section"><h4>Citizen review</h4><div className="feedback-summary"><strong>{average === null ? '—' : `${average.toFixed(1)}/5`}</strong><span>{currentReviews.length} reporter response<br />{flagged ? '⚑ Needs administrative review' : complaint.status === 'Citizen Verified' ? 'Ready for super admin review' : complaint.status === 'Finished' ? 'Filed as Finished work' : 'Awaiting confirmation'}</span></div>{currentReviews.map(f => <div className="drawer-review" key={f.id}><strong>{f.author} · {'★'.repeat(f.rating)}</strong><small>{f.resolution} resolved</small><p>{f.comment}</p></div>)}</div>}
    {canFeedback && <form className="detail-section action-card" onSubmit={sendFeedback}><h4>Verify the completed work</h4><p className="muted">Department staff marked this repair complete. Confirm what you see and rate the work.</p><div className="star-picker" aria-label="Rating out of five stars">{[1,2,3,4,5].map(n => <button type="button" key={n} aria-label={`${n} star${n === 1 ? '' : 's'}`} aria-pressed={rating === n} className={n <= rating ? 'selected' : ''} onClick={() => setRating(n)}>★</button>)}<span>{rating}/5</span></div><label>Was it resolved?<select value={resolution} onChange={e => setResolution(e.target.value)}>{['Yes','Partially','No'].map(x => <option key={x}>{x}</option>)}</select></label><label>Comment<textarea value={comment} onChange={e => setComment(e.target.value)} rows={3} placeholder="What changed on site?" /></label><button className="primary" disabled={busy}>Send verification and rating</button></form>}
    {reopenRequests.length > 0 && <div className="detail-section"><h4>Rework requests</h4>{reopenRequests.map(item => <div className="repair-evidence" key={item.id}><strong>{item.status} · {dateTime(item.created_at)}</strong><p>{item.reason}</p>{item.decision_note && <small>Owner decision: {item.decision_note}</small>}{data.user.role === 'superadmin' && item.status === 'Pending' && <div className="action-row"><button className="primary" disabled={busy || note.trim().length < 5} onClick={() => void decideRework(item.id, 'Approved')}>Approve rework</button><button className="secondary" disabled={busy || note.trim().length < 5} onClick={() => void decideRework(item.id, 'Declined')}>Decline</button></div>}</div>)}</div>}
    {data.user.role === 'citizen' && complaint.status === 'Finished' && complaint.finished_at && Date.now() - utcTime(complaint.finished_at).getTime() <= 14 * 86400000 && !reopenRequests.some(item => item.status === 'Pending') && <form className="detail-section action-card" onSubmit={askRework}><h4>Repair failed again?</h4><p className="muted">Within 14 days of Finished work, ask the owner to review this case for rework.</p><label>What failed again?<textarea minLength={12} required value={reworkReason} onChange={e => setReworkReason(e.target.value)} rows={3} /></label><button className="secondary" disabled={busy}>Request rework review</button></form>}
    {admin && <div className="detail-section action-card"><h4>Administrator actions</h4><label>Note<textarea value={note} onChange={e => setNote(e.target.value)} rows={2} placeholder="Reason or instruction for the timeline" /></label>{['Submitted','Under Review'].includes(complaint.status) && <><div className="action-row"><button className="primary" disabled={busy} onClick={() => void perform('verify')}><Check size={15} /> Verify</button><button className="secondary danger" disabled={busy} onClick={() => void perform('reject')}>Reject</button></div>{nearby.length > 0 && <><label>Nearby report in the same category<select value={duplicateId} onChange={e => setDuplicateId(e.target.value)}><option value="">Choose an original report</option>{nearby.map(row => <option key={row.id} value={row.id}>{row.code} · {row.title} ({row.distance} m)</option>)}</select></label><button className="secondary" disabled={busy || !duplicateId} onClick={() => void perform('duplicate', { duplicateOf: Number(duplicateId) })}>Mark as duplicate</button></>}</>}{['Verified','Assigned','Reopened'].includes(complaint.status) && <><label>Assign department<select value={departmentId} onChange={e => setDepartmentId(e.target.value)}><option value="">Select department</option>{data.departments.filter(d => d.active).map(d => <option value={d.id} key={d.id}>{d.name}</option>)}</select></label><button className="primary" disabled={busy || !departmentId} onClick={() => void perform('assign', { departmentId: Number(departmentId) })}>Assign department</button></>}
    <label>Priority<select value={priority} onChange={e => setPriority(e.target.value)}>{['Normal','High','Urgent'].map(x => <option key={x}>{x}</option>)}</select></label><button className="secondary" disabled={busy} onClick={() => void perform('priority', { priority })}>Update priority</button>{complaint.recurrence_flag && <button className="secondary" disabled={busy || note.trim().length < 5} onClick={() => void perform('dismissRecurrence')}>Dismiss recurrence flag</button>}
    {complaint.status === 'Citizen Verified' && data.user.role === 'superadmin' && <button className="primary" disabled={busy} onClick={() => void perform('finish')}>Move to Finished work</button>}{['Awaiting Feedback','Citizen Verified','Closed'].includes(complaint.status) && <button className="secondary danger" disabled={busy || note.trim().length < 5} onClick={() => void perform('reopen')}>Reopen case</button>}{complaint.status === 'Finished' && data.user.role === 'superadmin' && <button className="secondary danger" disabled={busy || note.trim().length < 5} onClick={() => void perform('reopen')}>Reopen finished case</button>}</div>}
    {staff && ['Assigned','Reopened','In Progress'].includes(complaint.status) && <div className="detail-section action-card"><h4>Department work</h4><label>Work note<textarea value={note} onChange={e => setNote(e.target.value)} rows={3} placeholder="What has been done?" /></label>{['Assigned','Reopened'].includes(complaint.status) && <button className="primary" disabled={busy} onClick={() => void perform('start')}>Start work</button>}{complaint.status === 'In Progress' && <><button className="secondary" disabled={busy} onClick={() => void perform('progress')}>Add progress note</button><label className="inline-upload"><Upload size={17} /> Completion photo required<input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e => { try { setCompletionImage(e.target.files?.[0] ? await readImage(e.target.files[0]) : null); } catch (err) { showError(String(err)); } }} /></label>{completionImage && <small className="success-text">Photo ready to attach</small>}<button className="primary" disabled={busy || !completionImage || note.trim().length < 5} onClick={() => void perform('resolve', { image: completionImage })}>Mark work completed</button></>}</div>}
    <div className="detail-section"><h4>Activity timeline</h4><div className="timeline">{[...updates.map(u => ({ key: `u${u.id}`, action: u.action, actor: u.actor, note: u.note, created_at: u.created_at })),...escalationEvents.map(e => ({ key: `e${e.id}`, action: `Deadline ${e.stage.toLowerCase()}`, actor: 'CivicPulse', note: e.message, created_at: e.created_at }))].sort((a,b) => b.created_at.localeCompare(a.created_at)).map(u => <div key={u.key}><span className="timeline-point" /><div><strong>{u.action}</strong><small>{u.actor} · {date(u.created_at)}</small>{u.note && <p>{u.note}</p>}</div></div>)}</div></div>
  </div></aside></div>;
}

export default function App() {
  const [user, setUser] = useState<User | null>(null); const [data, setData] = useState<Snapshot | null>(null);
  const [setupRequired, setSetupRequired] = useState(false);
  const [emailEnabled, setEmailEnabled] = useState(false); const [backupEnabled, setBackupEnabled] = useState(false);
  const [pushPublicKey, setPushPublicKey] = useState<string | null>(null);
  const [turnstileSiteKey, setTurnstileSiteKey] = useState<string | null>(null);
  const [accountLink, setAccountLink] = useState<{ purpose: 'verify' | 'reset'; token: string } | null>(() => { const match = location.hash.match(/^#(verify|reset)=([A-Za-z0-9_-]{43})$/); return match ? { purpose: match[1] as 'verify' | 'reset', token: match[2] } : null; });
  const [page, setPage] = useState<Page>('dashboard'); const [selectedId, setSelectedId] = useState<number | null>(null);
  const [detail, setDetail] = useState<ComplaintDetail | null>(null);
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true);
  const [signOutOpen, setSignOutOpen] = useState(false); const [signOutBusy, setSignOutBusy] = useState(false);
  const [refreshBusy, setRefreshBusy] = useState(false);
  const [lastRefresh, setLastRefresh] = useState('');
  const refresh = useCallback(async () => { const snapshot = await request<Snapshot>('snapshot'); setData(snapshot); setUser(snapshot.user); }, []);
  useEffect(() => { if (accountLink) history.replaceState(null, '', location.pathname + location.search); }, []);
  useEffect(() => { void Promise.all([request<{ setupRequired?: boolean; emailEnabled?: boolean; offsiteBackupEnabled?: boolean; pushPublicKey?: string | null; turnstileSiteKey?: string | null }>('config'), request<User | null>('session')]).then(async ([config, account]) => { setSetupRequired(Boolean(config.setupRequired)); setEmailEnabled(Boolean(config.emailEnabled)); setBackupEnabled(Boolean(config.offsiteBackupEnabled)); setPushPublicKey(config.pushPublicKey || null); setTurnstileSiteKey(config.turnstileSiteKey || null); if (account) { setUser(account); await refresh(); } }).catch(err => setError(String(err))).finally(() => setLoading(false)); }, [refresh]);
  useEffect(() => { if (user?.id && pushPublicKey && pushAvailable() && Notification.permission === 'granted') void enablePush(pushPublicKey).catch(() => {}); }, [user?.id,pushPublicKey]);
  useEffect(() => {
    if (!user?.id) return;
    let active = true;
    const update = () => {
      if (document.visibilityState !== 'visible') return;
      void request<Snapshot>('snapshot').then(snapshot => { if (active && snapshot.user.id === user.id) setData(snapshot); }).catch(() => {});
      if (selectedId !== null) void request<ComplaintDetail>('complaintDetail', { id: selectedId }).then(next => { if (active) setDetail(next); }).catch(() => {});
    };
    const timer = window.setInterval(update, 90000);
    window.addEventListener('focus', update);
    document.addEventListener('visibilitychange', update);
    return () => { active = false; window.clearInterval(timer); window.removeEventListener('focus', update); document.removeEventListener('visibilitychange', update); };
  }, [user?.id, selectedId]);
  useEffect(() => onNotice(message => { setNotice(message); setTimeout(() => setNotice(''), 4500); }), []);
  useEffect(() => { window.scrollTo(0, 0); }, [page, user?.id]);
  const login = async (email: string, password: string) => { setBusy(true); setError(''); try { const account = await request<User>('login', { email, password }); setUser(account); setPage('dashboard'); setSelectedId(null); await refresh(); } catch (err) { setError(String(err instanceof Error ? err.message : err)); } finally { setBusy(false); } };
  const register = async (details: { name: string; email: string; area: string; password: string }) => { setBusy(true); setError(''); try { const account = await request<User>('register', details); setUser(account); setPage('dashboard'); await refresh(); } catch (err) { setError(String(err instanceof Error ? err.message : err)); } finally { setBusy(false); } };
  const setup = async (details: { key: string; name: string; email: string; password: string }) => { setBusy(true); setError(''); try { const account = await request<User>('bootstrap', details); setUser(account); setSetupRequired(false); await refresh(); } catch (err) { setError(String(err instanceof Error ? err.message : err)); } finally { setBusy(false); } };
  const logout = async () => { setSignOutBusy(true); try { await request('logout'); setSignOutOpen(false); setUser(null); setData(null); setPage('dashboard'); setSelectedId(null); setDetail(null); setError(''); } catch (err) { showError(String(err instanceof Error ? err.message : err)); } finally { setSignOutBusy(false); } };
  const showError = (message: string) => { setError(message); setTimeout(() => setError(''), 7000); };
  const forgot = async (email: string) => { setBusy(true); setError(''); try { await request('forgotPassword', { email }); return true; } catch (err) { setError(String(err instanceof Error ? err.message : err)); return false; } finally { setBusy(false); } };
  const recoverWithCode = async (code: string, newPassword: string) => { setBusy(true); setError(''); try { await request('recoverWithCode', { code, newPassword }); return true; } catch (err) { setError(String(err instanceof Error ? err.message : err)); return false; } finally { setBusy(false); } };
  const refreshNow = async () => { if (refreshBusy) return; setRefreshBusy(true); setLastRefresh(''); try { await refresh(); window.dispatchEvent(new Event('civic:refresh')); if (selectedId !== null) setDetail(await request<ComplaintDetail>('complaintDetail', { id: selectedId })); setLastRefresh(`Updated ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}`); setNotice('Shared reports refreshed.'); setTimeout(() => setNotice(''), 4000); } catch (err) { showError(String(err instanceof Error ? err.message : err)); setLastRefresh('Refresh failed'); } finally { setRefreshBusy(false); } };
  const open = (id: number) => { setSelectedId(id); setDetail(null); void request<ComplaintDetail>('complaintDetail', { id }).then(setDetail).catch(err => showError(String(err))); };
  const refreshDetail = async () => { await refresh(); if (selectedId !== null) setDetail(await request<ComplaintDetail>('complaintDetail', { id: selectedId })); };
  const selected = detail?.complaint && detail.complaint.id === selectedId ? detail.complaint : null;
  const nav = useMemo(() => {
    const base: Array<[Page,string,ReactNode]> = [['dashboard','Overview',<LayoutDashboard size={19} />],['complaints','Complaints',<FileText size={19} />]];
    if (user?.role === 'citizen') base.push(['report','Report an issue',<Plus size={19} />]);
    base.push(['notifications','Notifications',<Bell size={19} />]);
    base.push(['map','Issue map',<MapIcon size={19} />],['feedback','Community feedback',<MessageSquare size={19} />],['analytics','Analytics',<BarChart3 size={19} />]);
    if (user?.role === 'superadmin') base.push(['performance','Finished work',<BarChart3 size={19} />],['manage','Administration',<Settings size={19} />]);
    base.push(['profile','Account security',<ShieldCheck size={19} />]);
    return base;
  }, [user?.role]);
  if (loading) return <div className="loading-screen"><div className="loading-logo"><Activity size={35} /></div><span>Loading CivicPulse…</span></div>;
  if (accountLink) return <AccountLink purpose={accountLink.purpose} token={accountLink.token} onDone={() => { const wasReset = accountLink.purpose === 'reset'; setAccountLink(null); if (wasReset) { setUser(null); setData(null); } else if (user) void refresh(); }} />;
  if (setupRequired) return <OwnerSetup onSetup={setup} busy={busy} error={error} />;
  if (!user || !data) return <Login onLogin={login} onRegister={register} onForgot={forgot} onRecoverCode={recoverWithCode} emailEnabled={emailEnabled} turnstileSiteKey={turnstileSiteKey} busy={busy} error={error} />;
  return <div className="shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><MapPin size={20} /></span><span>CivicPulse</span></div><div className="workspace-label">WORKSPACE</div><nav>{nav.map(([key,label,icon]) => <button key={key} className={page === key ? 'active' : ''} onClick={() => { setPage(key); setSelectedId(null); }} aria-label={label} title={label}>{icon}<span>{label}</span>{key === 'notifications' && data.notifications.filter(item => !item.read_at).length > 0 && <i className="nav-count">{data.notifications.filter(item => !item.read_at).length}</i>}{key === 'complaints' && (data.summary.counts.pending || 0) > 0 && ['admin','superadmin'].includes(user.role) && <i className="nav-count">{data.summary.counts.pending || 0}</i>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-tip"><span><Activity size={17} /> DHAKA SIGNAL</span><strong>{data.summary.counts.open || 0} active reports</strong><small>In the Dhaka service area</small></div><button className="profile-mini" onClick={() => setSignOutOpen(true)} title="Sign out" aria-label="Sign out"><span className="profile-avatar">{user.name[0]}</span><span><strong>{user.name}</strong><small>{roleName[user.role]}</small></span><LogOut size={17} /></button></div></aside><div className="main-area"><header className="topbar"><div className="breadcrumb">CivicPulse <span>/</span> <strong>{nav.find(n => n[0] === page)?.[1]}</strong></div><div className="top-actions"><button type="button" className="notification-trigger" onClick={() => setPage('notifications')} aria-label={`${data.notifications.filter(item => !item.read_at).length} unread notifications`}><Bell size={17} /> {data.notifications.filter(item => !item.read_at).length} unread</button>{user.role !== 'citizen' && <span className="today">{user.role === 'superadmin' ? (data.summary.counts.citizen_verified || 0) + ' ready to finish' : (data.summary.counts.pending || 0) + ' new reports'}</span>}<span className="top-date">{new Date().toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'long' })}</span><span className="refresh-status" role="status" aria-live="polite">{lastRefresh}</span><button type="button" className="refresh-button" disabled={refreshBusy} onClick={() => void refreshNow()} title="Refresh shared data"><Activity size={15} /> {refreshBusy ? 'Refreshing…' : 'Refresh'}</button><button type="button" className="top-avatar" aria-label="Account security" title="Account security" onClick={() => { setPage('profile'); setSelectedId(null); }}>{user.name[0]}</button></div></header><main className="content">
    {page === 'dashboard' && <Dashboard data={data} onPage={setPage} onOpen={open} />}
    {page === 'complaints' && <Complaints data={data} onOpen={open} />}
    {page === 'report' && <Report data={data} showError={showError} turnstileSiteKey={turnstileSiteKey} onCreated={async id => { await refresh(); setPage('complaints'); open(id); setNotice('Complaint submitted successfully.'); setTimeout(() => setNotice(''), 5000); }} />}
    {page === 'notifications' && <NotificationsPage data={data} onOpen={open} refresh={refresh} showError={showError} />}
    {page === 'map' && <MapPage data={data} onOpen={open} />}
    {page === 'feedback' && <FeedbackPage data={data} onOpen={open} />}
    {page === 'analytics' && <Analytics data={data} />}
    {page === 'performance' && user.role === 'superadmin' && <PerformancePage data={data} onPage={setPage} onOpen={open} showError={showError} />}
    {page === 'profile' && <Profile user={user} showError={showError} emailEnabled={emailEnabled} pushPublicKey={pushPublicKey} />}
    {page === 'manage' && user.role === 'superadmin' && <Manage data={data} refresh={refresh} showError={showError} backupEnabled={backupEnabled} />}
    {['admin','superadmin'].includes(user.role) && <div className="export-bar"><span>Need a copy of the current data?</span><button className="secondary" onClick={() => void request('exportCsv').catch(err => showError(String(err)))}><Download size={16} /> Export CSV</button><button className="secondary" onClick={() => void request('exportPdf').catch(err => showError(String(err)))}><Download size={16} /> Save PDF</button></div>}
  </main></div>{selected && detail && <Detail key={`${selected.id}-${user.id}`} data={{ ...data, updates: detail.updates, cycles: detail.cycles, feedback: detail.feedback }} complaint={selected} recurrence={detail.recurrence} escalationEvents={detail.escalationEvents || []} reopenRequests={detail.reopenRequests || []} onClose={() => { setSelectedId(null); setDetail(null); }} refresh={refreshDetail} showError={showError} />}{error && <div className="toast error-toast" role="alert"><Flag size={17} /> {error}<button onClick={() => setError('')} aria-label="Dismiss error"><X size={15} /></button></div>}{notice && <div className="toast success-toast" role="status"><Check size={17} /> {notice}</div>}{signOutOpen && <div className="confirm-backdrop" onClick={() => !signOutBusy && setSignOutOpen(false)}><div className="confirm-card" role="dialog" aria-modal="true" aria-labelledby="signout-title" onClick={event => event.stopPropagation()}><span className="eyebrow">ACCOUNT</span><h2 id="signout-title">Sign out of CivicPulse?</h2><p>You can sign in again to continue your work.</p><div className="confirm-actions"><button type="button" className="secondary" disabled={signOutBusy} onClick={() => setSignOutOpen(false)}>Stay signed in</button><button type="button" className="primary" disabled={signOutBusy} onClick={() => void logout()}>{signOutBusy ? 'Signing out…' : 'Sign out'}</button></div></div></div>}</div>;
}
